# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    npm run build
  displayName: 'npm install and build'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Production Azure Subscription - PIC(1)(61443faf-a8ba-460f-8344-dabe49fe1c6d)'
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
        az storage blob upload-batch \
          --destination \$web \
          --account-name "nextimedemos" \
          --source "$(Agent.BuildDirectory)/dest"